# .github/FUNDING.yml
github: sproctor
# ko_fi: your-kofi-username
# open_collective: warlock3
liberapay: sproctor
# buy_me_a_coffee: your-bmac-username
# patreon: your-patreon-username
# polar: sproctor
# custom: ["https://example.com/donate"]
