package warlockfe.warlock3.compose.ui.window

import androidx.compose.foundation.Canvas
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.material3.LocalContentColor
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.lerp
import androidx.compose.ui.text.LinkAnnotation
import androidx.compose.ui.text.buildAnnotatedString
import androidx.compose.ui.text.drawText
import androidx.compose.ui.text.rememberTextMeasurer
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.Constraints
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import coil3.compose.AsyncImage
import warlockfe.warlock3.compose.model.SkinColor
import warlockfe.warlock3.compose.model.SkinObject
import warlockfe.warlock3.compose.util.LocalSkin
import warlockfe.warlock3.compose.util.getColorGroup
import warlockfe.warlock3.compose.util.toColor
import warlockfe.warlock3.core.client.DataDistance
import warlockfe.warlock3.core.client.PanelObject
import warlockfe.warlock3.core.client.Percentage
import warlockfe.warlock3.core.text.StyleDefinition
import warlockfe.warlock3.core.util.getIgnoringCase
import kotlin.io.encoding.Base64

@Preview
@Composable
private fun VitalBarsPreview() {
    CompositionLocalProvider(
        LocalSkin provides
            mapOf(
                "HealthBar" to
                    SkinObject(
                        children =
                            mapOf(
                                "health" to
                                    SkinObject(
                                        color = SkinColor("#FFFFFF"),
                                        bar = SkinColor("#800000"),
                                        background = SkinColor("#444444"),
                                    ),
                            ),
                    ),
            ),
    ) {
        val panelData =
            listOf(
                PanelObject.Skin(
                    id = "healthSkin",
                    left = null,
                    top = null,
                    width = null,
                    height = null,
                    align = null,
                    topAnchor = null,
                    leftAnchor = null,
                    tooltip = null,
                    name = "healthBar",
                    controls = listOf("health"),
                ),
                PanelObject.ProgressBar(
                    id = "health",
                    left = DataDistance.Percent(value = Percentage(value = 0)),
                    top = DataDistance.Percent(value = Percentage(value = 0)),
                    width = DataDistance.Percent(value = Percentage(value = 25)),
                    height = DataDistance.Percent(value = Percentage(value = 100)),
                    align = null,
                    topAnchor = null,
                    leftAnchor = null,
                    tooltip = null,
                    value = Percentage(value = 50),
                    text = "health 13/26",
                ),
                PanelObject.Skin(
                    id = "manaSkin",
                    left = DataDistance.Percent(value = Percentage(value = 25)),
                    top = DataDistance.Percent(value = Percentage(value = 0)),
                    width = DataDistance.Percent(value = Percentage(value = 25)),
                    height = DataDistance.Percent(value = Percentage(value = 100)),
                    align = null,
                    topAnchor = null,
                    leftAnchor = null,
                    tooltip = null,
                    name = "manaBar",
                    controls = listOf("mana"),
                ),
                PanelObject.ProgressBar(
                    id = "mana",
                    left = DataDistance.Percent(value = Percentage(value = 25)),
                    top = DataDistance.Percent(value = Percentage(value = 0)),
                    width = DataDistance.Percent(value = Percentage(value = 25)),
                    height = DataDistance.Percent(value = Percentage(value = 100)),
                    align = null,
                    topAnchor = null,
                    leftAnchor = null,
                    tooltip = null,
                    value = Percentage(value = 100),
                    text = "mana 2/2",
                ),
                PanelObject.Skin(
                    id = "spiritSkin",
                    left = DataDistance.Percent(value = Percentage(value = 75)),
                    top = DataDistance.Percent(value = Percentage(value = 0)),
                    width = DataDistance.Percent(value = Percentage(value = 25)),
                    height = DataDistance.Percent(value = Percentage(value = 100)),
                    align = null,
                    topAnchor = null,
                    leftAnchor = null,
                    tooltip = null,
                    name = "spiritBar",
                    controls = listOf("spirit"),
                ),
                PanelObject.ProgressBar(
                    id = "spirit",
                    left = DataDistance.Percent(value = Percentage(value = 75)),
                    top = DataDistance.Percent(value = Percentage(value = 0)),
                    width = DataDistance.Percent(value = Percentage(value = 25)),
                    height = DataDistance.Percent(value = Percentage(value = 100)),
                    align = null,
                    topAnchor = null,
                    leftAnchor = null,
                    tooltip = null,
                    value = Percentage(value = 100),
                    text = "spirit 7/7",
                ),
                PanelObject.Skin(
                    id = "staminaSkin",
                    left = DataDistance.Percent(value = Percentage(value = 50)),
                    top = DataDistance.Percent(value = Percentage(value = 0)),
                    width = DataDistance.Percent(value = Percentage(value = 25)),
                    height = DataDistance.Percent(value = Percentage(value = 100)),
                    align = null,
                    topAnchor = null,
                    leftAnchor = null,
                    tooltip = null,
                    name = "staminaBar",
                    controls = listOf("stamina"),
                ),
                PanelObject.ProgressBar(
                    id = "stamina",
                    left = DataDistance.Percent(value = Percentage(value = 50)),
                    top = DataDistance.Percent(value = Percentage(value = 0)),
                    width = DataDistance.Percent(value = Percentage(value = 25)),
                    height = DataDistance.Percent(value = Percentage(value = 100)),
                    align = null,
                    topAnchor = null,
                    leftAnchor = null,
                    tooltip = null,
                    value = Percentage(value = 100),
                    text = "stamina 26/26",
                ),
            )
        PanelContent(
            dataObjects = panelData,
            modifier = Modifier.size(400.dp, 24.dp),
            onAction = {},
            style = StyleDefinition(),
        )
    }
}

@Preview
@Composable
private fun CombatPanelPreview() {
    val panelData =
        listOf(
            PanelObject.Image(
                id = "unsheathe",
                left = DataDistance.Pixels(value = -50),
                top = DataDistance.Pixels(value = 3),
                width = DataDistance.Pixels(value = 29),
                height = DataDistance.Pixels(value = 29),
                align = "n",
                topAnchor = null,
                leftAnchor = null,
                tooltip = "Unsheathe Weapon",
                name = "SwordBtn",
                cmd = "_ready weapon",
                echo = "ready weapon",
            ),
            PanelObject.Image(
                id = "readyshield",
                left = DataDistance.Pixels(value = 3),
                top = null,
                width = DataDistance.Pixels(value = 29),
                height = DataDistance.Pixels(value = 29),
                align = null,
                topAnchor = null,
                leftAnchor = "unsheathe",
                tooltip = "Ready Shield",
                name = "ShieldBtn",
                cmd = "_ready shield",
                echo = "ready shield",
            ),
            PanelObject.Image(
                id = "sheathe",
                left = DataDistance.Pixels(value = 8),
                top = null,
                width = DataDistance.Pixels(value = 29),
                height = DataDistance.Pixels(value = 29),
                align = null,
                topAnchor = null,
                leftAnchor = "readyshield",
                tooltip = "Sheathe Weapon",
                name = "NoSwordBtn",
                cmd = "_store weapon",
                echo = "store weapon",
            ),
            PanelObject.Image(
                id = "storeshield",
                left = DataDistance.Pixels(value = 3),
                top = null,
                width = DataDistance.Pixels(value = 29),
                height = DataDistance.Pixels(value = 29),
                align = null,
                topAnchor = null,
                leftAnchor = "sheathe",
                tooltip = "Store Shield",
                name = "NoShieldBtn",
                cmd = "_store shield",
                echo = "store shield",
            ),
            PanelObject.Link(
                id = "lnConfigure",
                left = DataDistance.Pixels(value = 0),
                top = DataDistance.Pixels(value = 30),
                width = null,
                height = null,
                align = "n",
                topAnchor = null,
                leftAnchor = null,
                tooltip = null,
                value = "configure",
                cmd = "_cmbtpl configure dialog",
                echo = "configure",
            ),
            PanelObject.ProgressBar(
                id = "pbarStance",
                left = DataDistance.Pixels(value = 0),
                top = DataDistance.Pixels(value = 51),
                width = DataDistance.Pixels(value = 130),
                height = DataDistance.Pixels(value = 16),
                align = "n",
                topAnchor = null,
                leftAnchor = null,
                tooltip = "Percent of stance contributing to defense",
                value = Percentage(value = 100),
                text = "defensive(100 %)",
            ),
            PanelObject.Button(
                id = "cmdDefStance",
                left = DataDistance.Pixels(value = 0),
                top = DataDistance.Pixels(value = 70),
                width = DataDistance.Pixels(value = 55),
                height = DataDistance.Pixels(value = 20),
                align = "nw",
                topAnchor = null,
                leftAnchor = null,
                tooltip = "Assume a Defensive Stance",
                value = "defense",
                cmd = "_stance defensive",
                echo = "stance defensive",
            ),
            PanelObject.Button(
                id = "cmdOffStance",
                left = DataDistance.Pixels(value = 0),
                top = DataDistance.Pixels(value = 70),
                width = DataDistance.Pixels(value = 50),
                height = DataDistance.Pixels(value = 20),
                align = "ne",
                topAnchor = null,
                leftAnchor = null,
                tooltip = "Assume an Offensive Stance",
                value = "offense",
                cmd = "_stance offensive",
                echo = "stance offensive",
            ),
            PanelObject.Button(
                id = "cmdTarget",
                left = DataDistance.Pixels(value = 0),
                top = DataDistance.Pixels(value = 93),
                width = DataDistance.Pixels(value = 55),
                height = DataDistance.Pixels(value = 20),
                align = "nw",
                topAnchor = null,
                leftAnchor = null,
                tooltip = "Select a Random Target",
                value = "target",
                cmd = "target random",
                echo = null,
            ),
            PanelObject.Button(
                id = "cmdAttack",
                left = DataDistance.Pixels(value = 0),
                top = DataDistance.Pixels(value = 93),
                width = DataDistance.Pixels(value = 50),
                height = DataDistance.Pixels(value = 20),
                align = "ne",
                topAnchor = null,
                leftAnchor = null,
                tooltip = "Attack Current Target",
                value = "attack",
                cmd = "attack",
                echo = null,
            ),
            PanelObject.Button(
                id = "cmdHide",
                left = DataDistance.Pixels(value = 0),
                top = DataDistance.Pixels(value = 116),
                width = DataDistance.Pixels(value = 55),
                height = DataDistance.Pixels(value = 20),
                align = "nw",
                topAnchor = null,
                leftAnchor = null,
                tooltip = "Hide",
                value = "hide",
                cmd = "hide",
                echo = null,
            ),
            PanelObject.Button(
                id = "cmdAmbush",
                left = DataDistance.Pixels(value = 0),
                top = DataDistance.Pixels(value = 116),
                width = DataDistance.Pixels(value = 50),
                height = DataDistance.Pixels(value = 20),
                align = "ne",
                topAnchor = null,
                leftAnchor = null,
                tooltip = "Ambush Current Target",
                value = "ambush",
                cmd = "ambush",
                echo = null,
            ),
            PanelObject.Button(
                id = "cmdJab",
                left = DataDistance.Pixels(value = 0),
                top = DataDistance.Pixels(value = 139),
                width = DataDistance.Pixels(value = 38),
                align = null,
                height = null,
                topAnchor = null,
                leftAnchor = null,
                tooltip = "Jab Current Target",
                value = "jab",
                cmd = "jab",
                echo = null,
            ),
            PanelObject.Button(
                id = "cmdPunch",
                left = DataDistance.Pixels(value = 38),
                top = DataDistance.Pixels(value = 139),
                width = DataDistance.Pixels(value = 53),
                align = null,
                height = null,
                topAnchor = null,
                leftAnchor = null,
                tooltip = "Punch Current Target",
                value = "punch",
                cmd = "punch",
                echo = null,
            ),
            PanelObject.Button(
                id = "cmdGrapple",
                left = DataDistance.Pixels(value = 91),
                top = DataDistance.Pixels(value = 139),
                width = DataDistance.Pixels(value = 59),
                align = null,
                height = null,
                topAnchor = null,
                leftAnchor = null,
                tooltip = "Grapple Current Target",
                value = "grapple",
                cmd = "grapple",
                echo = null,
            ),
            PanelObject.Button(
                id = "cmdKick",
                left = DataDistance.Pixels(value = 150),
                top = DataDistance.Pixels(value = 139),
                width = DataDistance.Pixels(value = 40),
                height = null,
                align = null,
                topAnchor = null,
                leftAnchor = null,
                tooltip = "Kick Current Target",
                value = "kick",
                cmd = "kick",
                echo = null,
            ),
            PanelObject.Button(
                id = "cmdQuickstrike",
                left = DataDistance.Pixels(value = 53),
                top = DataDistance.Pixels(value = 165),
                width = DataDistance.Pixels(value = 137),
                height = DataDistance.Pixels(value = 20),
                align = null,
                topAnchor = null,
                leftAnchor = null,
                tooltip = "Quickstrike Next Action",
                value = "prepare to quickstrike",
                cmd = "quickstrike % uDEQuickstrike %",
                echo = null,
            ),
            PanelObject.Link(
                id = "lnSkin",
                left = DataDistance.Pixels(value = 0),
                top = DataDistance.Pixels(value = 191),
                width = null,
                height = null,
                align = null,
                topAnchor = null,
                leftAnchor = null,
                tooltip = null,
                value = "skin",
                cmd = "_skin",
                echo = "skin",
            ),
            PanelObject.Link(
                id = "lnSearch",
                left = null,
                top = null,
                width = null,
                height = null,
                align = null,
                topAnchor = null,
                leftAnchor = null,
                tooltip = null,
                value = "search",
                cmd = "_search",
                echo = "search",
            ),
            PanelObject.Link(
                id = "lnGrip",
                left = null,
                top = null,
                width = null,
                height = null,
                align = null,
                topAnchor = null,
                leftAnchor = null,
                tooltip = null,
                value = "grip",
                cmd = "_grip",
                echo = "grip",
            ),
        )
    PanelContent(
        dataObjects = panelData,
        modifier = Modifier.size(190.dp, 219.dp),
        onAction = {},
        style = StyleDefinition(),
    )
}

@Preview
@Composable
private fun ExperiencePreview() {
    val panelData =
        listOf(
            PanelObject.Label(
                id = "yourLvl",
                left = DataDistance.Pixels(value = 0),
                top = DataDistance.Pixels(value = 0),
                width = DataDistance.Pixels(value = 160),
                height = DataDistance.Pixels(value = 15),
                align = "n",
                topAnchor = null,
                leftAnchor = null,
                tooltip = null,
                value = "Level 0",
            ),
            PanelObject.ProgressBar(
                id = "mindState",
                left = DataDistance.Pixels(value = 3),
                top = DataDistance.Pixels(value = 45),
                width = DataDistance.Pixels(value = 160),
                height = DataDistance.Pixels(value = 15),
                align = "n",
                topAnchor = null,
                leftAnchor = null,
                tooltip = null,
                value = Percentage(value = 0),
                text = "clear as a bell",
            ),
            PanelObject.ProgressBar(
                id = "nextLvlPB",
                left = DataDistance.Pixels(value = 3),
                top = DataDistance.Pixels(value = 20),
                width = DataDistance.Pixels(value = 160),
                height = DataDistance.Pixels(value = 15),
                align = "n",
                topAnchor = null,
                leftAnchor = null,
                tooltip = null,
                value = Percentage(value = 6),
                text = "2365 until next level",
            ),
            PanelObject.Label(
                id = "PTPs",
                left = DataDistance.Pixels(value = 20),
                top = DataDistance.Pixels(value = 0),
                width = DataDistance.Pixels(value = 80),
                height = DataDistance.Pixels(value = 20),
                align = null,
                topAnchor = "mindState",
                leftAnchor = null,
                tooltip = "Physical Training Points",
                value = "5 PTPs",
            ),
            PanelObject.Label(
                id = "MTPs",
                left = DataDistance.Pixels(value = 0),
                top = DataDistance.Pixels(value = 0),
                width = DataDistance.Pixels(value = 80),
                height = DataDistance.Pixels(value = 20),
                align = null,
                topAnchor = "mindState",
                leftAnchor = "PTPs",
                tooltip = "Mental Training Points",
                value = "3 MTPs",
            ),
            PanelObject.Label(
                id = "p2m",
                left = DataDistance.Pixels(value = 20),
                top = DataDistance.Pixels(value = 0),
                width = DataDistance.Pixels(value = 80),
                height = DataDistance.Pixels(value = 20),
                align = null,
                topAnchor = "PTPs",
                leftAnchor = null,
                tooltip = "Physical tps that have been converted to Mental tps",
                value = "0 P2M",
            ),
            PanelObject.Label(
                id = "m2p",
                left = DataDistance.Pixels(value = 0),
                top = DataDistance.Pixels(value = 0),
                width = DataDistance.Pixels(value = 80),
                height = DataDistance.Pixels(value = 20),
                align = null,
                topAnchor = "MTPs",
                leftAnchor = "p2m",
                tooltip = "Mental tps that have been converted to Physical tps",
                value = "0 M2P",
            ),
            PanelObject.Link(
                id = "exprLNK",
                left = DataDistance.Pixels(value = 20),
                top = DataDistance.Pixels(value = 0),
                width = DataDistance.Pixels(value = 80),
                height = null,
                align = null,
                topAnchor = "p2m",
                leftAnchor = null,
                tooltip = null,
                value = "Details",
                cmd = "experie",
                echo = "experience",
            ),
            PanelObject.Link(
                id = "goalsLNK",
                left = DataDistance.Pixels(value = 0),
                top = DataDistance.Pixels(value = 0),
                width = DataDistance.Pixels(value = 80),
                height = null,
                align = null,
                topAnchor = "m2p",
                leftAnchor = "exprLNK",
                tooltip = null,
                value = "Skill Goals",
                cmd = "goals",
                echo = "goals",
            ),
        )
    PanelContent(
        dataObjects = panelData,
        modifier = Modifier.size(190.dp, 200.dp),
        onAction = {},
        style = StyleDefinition(),
    )
}
